databases:
  - name: prod
    region: frankfurt
    plan: free
    databaseName: resortodb
    user: resortodb_user

services:
  - type: web
    name: web
    env: ruby
    buildCommand: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"  && bash -c "bundle exec ruby ./Resorto/bin/setup"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prod
          property: postgres://resortodb_user:v3SGmkIIqdWTFDRotm85YpCR8KSQSDCv@dpg-cdt4sfta49935khcv4jg-a/resortodb